setxkbmap -layout gb 

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=""

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS=true

plugins=(git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh
fpath+=("$HOME/.zsh/pure")
autoload -U promptinit; promptinit

prompt pure

source $HOME/.env
source $HOME/.functions
source $HOME/.alias
